#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

function fibBinet(n)
  phi = (1+sqrt(5))/2
  phi_bar = (1-sqrt(5))/2
  return round((phi^n - phi_bar^n)/sqrt(5))
end

n=0
fib=fibBinet(n)
runSum=0
while fib < 4000000
  if fib%2 == 0
    runSum += fib
  end
  n += 1
  fib = fibBinet(n)
end

print(runSum)
