# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n-1)      1, 6, 15, 28, 45  ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

def generateL(limit):
	triL = []
	pentL = []
	hexL = []
	for i in xrange(1,limit):
		triL.append(i*(i+1)/2)
		pentL.append(i*(3*i-1)/2)
		hexL.append(i*(2*i-1))
	return triL, pentL, hexL

triL, pentL, hexL = generateL(100000)
commonL = set(hexL)
commonL.intersection_update(pentL)
commonL.intersection_update(triL)
print commonL